package com.sntf.steps;

import java.nio.file.FileSystems;
import java.nio.file.Path;

import org.testng.annotations.Test;

import com.google.zxing.BarcodeFormat;
import com.google.zxing.client.j2se.MatrixToImageWriter;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.qrcode.QRCodeWriter;
import com.sntf.driver.SharedBrowser;

public class QRCodeGenerator extends SharedBrowser {

	@Test
	public void generateQRCODE() throws Exception {
		String QR_CODE_TEXT = "QR Code generated by CherCher Tech";
		// create object to QR code write
		QRCodeWriter qrCodeWriter = new QRCodeWriter();
		// set the content, type, size
		BitMatrix bitMatrix = qrCodeWriter.encode(QR_CODE_TEXT, BarcodeFormat.QR_CODE, 320, 320);
		// set the file
		Path path = FileSystems.getDefault()
				.getPath(System.getProperty("user.dir") + "/QRCODE-PNG/" + timestamp() + ".png");
		// System.getProperty("user.dir")+"/target/Screenshots/" + testCaseName + "_" +
		// timestamp() + ".png"))
		// write the image content into the given file
		MatrixToImageWriter.writeToPath(bitMatrix, "PNG", path);
	}
}
